import './globals.css';
import './custom.css'

export const metadata = {
  title: 'Pomodoro-keyhanil',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
     <html lang="en">
      <body>
      {children}
      </body>
    </html>
  )
}
